### ISSUE TITLE
报错报错！！！

### ISSUE THREAD

**Issue by laoquanshi** [TaleLin/lin-cms-vue#584]
Error: Cannot find module 'H:\shenjixiangmu\lin-cms-vue-master\install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
前端报错啊 受不了了
![image](https://github.com/TaleLin/lin-cms-vue/assets/110451039/0b1a7af0-a016-4465-a0fe-6d2a958bf126)

**Comment by vanoneang** [comment]
`install or yarn` 是个啥。。。
